module.exports = {
  STATUS_CODE: {
    OK: 200,
    TRIPLEA: 151,
    CREATED: 201,
    ACCEPTED: 202,
    NO_CONTENT: 204,
    INFO: 250,
    NON_AUTHORITATIVE: 203,
    BAD_REQUEST: 400,
    UN_AUTHORIZED: 401,
    FORBIDDEN: 403,
    RESOURCE_NOT_FOUND: 404,
    PROXY_AUTH_FAILED: 412,
    TOO_MANY_REQUESTS: 429,
    VALIDATION_FAILURE: 450,
    INTERNAL_SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503,
    SERVER_TIMEOUT: 504,
  },

  ERROR_MSGS: {
    INTERNAL_SERVER_ERROR: "Something went wrong. Please try again.",
    ACCOUNT_EXISTS: "Account already exists. Please login",
    ACCOUNT_NOT_EXISTS: "Email is not exists. Please sign up",
    WENT_WRONG: "Oops! Something went wrong.",
    INVALID_LOGIN: "Invalid email or/and password.",
    UPDATE_ERR: "Sorry, the data could not be updated.",
    CREATE_ERR: "Oops! Failed to create data.",
    DELETE_ERR: "Failed to delete data.",
    INVALID_ID: "Invalid User ID provided.",
    ALREADY_REMOVED: "Already removed.",
    INVALID_TOKEN_FORMAT: "Invalid token format.",
    TOKEN_MISSING: "Authorization required.",
    EXPIRED_OTP: "Your OTP has been Expired, Please resend",
    UN_AUTHORIZED: "Unauthorized token.",
    TOKEN_SESSION_EXPIRED: "Your session has expired. Please log in again.",
    INVALID_TOKEN: "Invalid or expired token.",
    INVALID_TOKEN_TYPE: "Invalid token type.",
    DATA_NOT_FOUND: "Data not found.",
    DATA_NOT_AVAILABLE: "Unable to find the requested data.",
    ACCOUNT_NOT_FOUND: "Account not found. Please register first.",
    PERMISSIONS_DENIED: "Access denied. Only admin can use this.",
    ADMIN_ACCESS_DENIED: "Access denied. Only admin can logged in.",
    FAVORITE_ALREADY_EXISTS: "This item is already marked as a favorite.",
    DATA_EXISTS: "already exists.",
    KEY_REQUIRED: "is required.",
    INVALID_OTP: "Invalid Otp",
    NOT_FOUND: "is not found",
    NOT_EDITABLE: "cannot be edited.",
    BAD_REQUEST: "Bad request.",
    INVALID_TYPE: "type is invalid",
    INVALID_EMAIL_OR_MOBILE: "Email is invalid",
    FILES_EMPTY: "Files cannot be empty",
    BODY_EMPTY: "Body cannot be empty",
    INSUFFICIENT_PERMISSION: "Insufficient permissions",
    NO_ACCESS_TOKEN: "Authentication Token Missing in Request Header",
    AUTHORIZATION_FAILED: "Authorization failed, please try again!",
    AUTHORIZATION_FAILED_LOGIN_AGAIN:
      "Authorization Failed, Please login again!!",
    INVALID_SORTBY: "Invalid sortBy value.",
    INVALID_ROLE: "Invalid role value.",
    UNSUPPORTED_FILE: "Unsupported file type",
    FORGOT_PASSWORD_TOKEN_EXPIRED:
      "Please initiate the password reset process again to receive a new otp.",
    ENVIRONMENT_VAR_MISSING: "Missing required environment variables.",
    ACCESS_RESTRICTED_ADMIN:
      "Access denied. Your account has been restricted by the administrator.",
    EMAIL_EXIST:
      "This email is already registered. Please use a different one.",
    ACCESS_TOKEN_REQUIRED:
      "Access token is required, but a refresh token was provided. Please provide a valid access token.",
  },

  INFO_MSGS: {
    CREATED_SUCCESSFULLY: "Data created successfully.",
    ADDED_SUCCESSFULLY: "Data added successfully.",
    UPDATED_SUCCESSFULLY: "Data updated successfully.",
    DELETED_SUCCESSFULLY: "Data deleted successfully.",
    UPLOADED_SUCCESSFULLY: "Data uploaded successfully.",
    VERIFY_SUCCESSFULLY: "verified successful.",
    UNVERIFY_SUCCESSFULLY: "unverified successful.",
    LOGOUT_SUCCESSFULLY: "Logout successfully.",
    SUCCESSFUL_LOGIN: "Successfully logged in.",
    SUCCESS: "Request successful.",
    OTP_VERIFIED: "Otp verified successfully.",
    PASSWORD_CHANGED: "Your password has been changed successfully.",
    SEND_USER_TO_CARRIER_REQUEST:
      "Your request is successfully send to carrier, wait for carrier to approve your request.",
    SUCCESSFUL_REGISTER: "Your registration with Cargo Connect is successful.",
    OTP_SENT_SUCC:
      "An OTP has been sent to your email address. Please check your inbox and use the OTP to proceed.",
    OTP_SENT_IN_MOBILE_SUCC:
      "An OTP has been sent to your mobile number. Please check your messages and use the OTP to proceed.",
  },
};
